### ISSUE TITLE
Regarding normalizing the phase angle in cordic.v

### ISSUE THREAD

**Issue by aklsh** [ZipCPU/cordic#2]
Hey,

I found this repository really good as reference to the whole CORDIC algorithm on how it works and stuff. 

But one doubt I have is how can you multiply the phase angle (`i_phase`) by 2^32/(2pi) when, it's only 20 bits wide (in the given default code PW = 20)? I mean, won't it just become 0 then (as you're shifting by 32 bits) ? I know this is a silly doubt to ask, but I didn't know where else to ask...

**Comment by ZipCPU** [comment]
I think you have that backwards.  To convert to radians, you want to multiply `i_phase` by 2pi/(2^32).  The result will not necessarily be an integer.  Of course it won't be--radians only exist between 0 and 2pi.

Dan
